# Generated by Django 5.1.1 on 2024-09-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("desccription", models.CharField(max_length=1000)),
                ("discount", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
